// routes/rfq.routes.js
const express = require("express");
const router = express.Router();
const { authMiddleware } = require("../middleware/authMiddleware");

const {
  createRFQ,
  getRFQs,
  getRFQById,
  updateRFQ,
  sendRfq,
  getRfqVendorEmail,
} = require("../controllers/ProjectModule/Rfq.controller");

// POST /api/rfq                     -> create new RFQ (supports dynamic user-added fields)
// rfq_number is auto-generated by the DB sequence unless explicitly passed in the body.
router.post("/", authMiddleware, createRFQ);

// GET /api/rfq                      -> get all RFQs (supports ?page=&limit=&project_code=)
router.get("/", authMiddleware, getRFQs);

// GET /api/rfq/:rfqNumber           -> get single RFQ by rfq_number (e.g. "RFQ-001")
router.get("/:rfqNumber", authMiddleware, getRFQById);

// PUT /api/rfq/:rfqNumber           -> update RFQ (also supports adding new dynamic fields)
// rfq_number itself can never be changed via this route — it's the primary key.
router.put("/:rfqNumber", authMiddleware, updateRFQ);

// GET /api/rfq/:rfqNumber/vendor-email -> reads vendor_name/email_id directly off the
// rfq row (no join anymore), used to pre-fill the "Send RFQ" modal
router.get("/:rfqNumber/vendor-email", authMiddleware, getRfqVendorEmail);

// POST /api/rfq/:rfqNumber/send     -> build PDF quotation + email it to vendor
router.post("/:rfqNumber/send", authMiddleware, sendRfq);

module.exports = router;